Repository fluffysheep-codeu/Summer2019-Team30, pull requests merged in 2019-07, with the labels that each got.

#102 Adding a restaurant to public feed now displays the markers on the map
  client/package-lock.json
  client/src/components/page/PublicFeed.js
  server/pom.xml
  server/src/main/java/com/google/codeu/data/Datastore.java
  server/src/main/java/com/google/codeu/data/Restaurant.java
  server/src/main/java/com/google/codeu/servlets/RestaurantServlet.java
Labels: build 0.04 - 06/30/19

#103 Fixing ckeditor bug for about me
  client/package-lock.json
  client/src/components/page/UserPage.js
  server/src/main/java/com/google/codeu/servlets/AboutMeServlet.java
Labels: build 0.05 - 07/17/19

#108 Restaurants to posts
  client/src/components/page/PublicFeed.js
  server/src/main/java/com/google/codeu/servlets/RestaurantServlet.java
Labels: build 0.05 - 07/19/19

#106 Adding styling to home page
  client/src/components/page/Home.js
  client/src/components/page/UserPage.js
Labels: build 0.05 - 07/19/19

#110 Restaurants now update correctly
  client/src/components/page/PublicFeed.js
  client/src/components/page/UserPage.js
Labels: build 0.05 - 07/19/19
