Repository fluffysheep-codeu/Summer2019-Team30, pull requests merged in 2019-05, with the labels that each got.

#19 Added name and description to contributors.js
  client/package-lock.json
  client/src/reducers/contributors.js
Labels: 0.0.1 - 05/26/19

#20 Reformat Alex's string description to fit 80 character count.
  client/src/reducers/contributors.js
Labels: Process

#21 Update git squash img with urls to PRs and Issues
  docs/images/git-squash-5.png
Labels: Process

#22 Adds profile pictures to About Team page.
  client/src/components/page/About.js
  client/src/components/ui/TeamIntroCard.js
  client/src/reducers/contributors.js
  client/src/statics/images/brianPic.jpeg
Labels: 0.0.1 - 05/26/19, Feature

#24 Brianch devguide
  docs/dev.md
  docs/images/dev01.png
  docs/images/dev02.png
  docs/images/dev03.png
  docs/images/dev04.png
  docs/images/dev05.png
  docs/images/dev06.png
  docs/images/dev07.png
  docs/images/dev08.png
  docs/images/dev09.png
  docs/images/dev10.png
  docs/images/dev11.png
Labels: Process

#25 Add a doc on terminal actions and commands
  docs/_layouts/default.html
  docs/commandline.md
Labels: Process

#23 Installed material-ui and update team cards to material cards
  client/package-lock.json
  client/package.json
  client/src/components/page/About.js
  client/src/components/ui/TeamIntroCard.js
  client/src/reducers/contributors.js
Labels: 0.0.1 - 05/26/19, Feature

#27 Added profile picture to about page
  client/src/reducers/contributors.js
  client/src/statics/images/alexPic.jpg
  server/src/main/java/com/google/codeu/data/Message.java
Labels: 0.0.1 - 05/26/19, Story

#30 Allows all URLs to be handled by React except for /api/ and /_ah/ URLs.
  client/src/components/page/UserPage.js
  client/src/constants/links.js
  client/src/setupProxy.js
  docs/overview.md
  server/src/main/java/com/google/codeu/filters/SinglePageAppFilter.java
  server/src/main/java/com/google/codeu/servlets/LoginServlet.java
  server/src/main/java/com/google/codeu/servlets/LoginStatusServlet.java
  server/src/main/java/com/google/codeu/servlets/LogoutServlet.java
  server/src/main/java/com/google/codeu/servlets/MessageServlet.java
Labels: build: 0.0.1 - 05/26/19, pr: bug

#28 Adding Samantha's bio and picture to contributors.js
  client/src/reducers/contributors.js
  client/src/statics/images/SamsPic2.JPG
Labels: build: 0.0.1 - 05/26/19, pr: feature

#31 Update README.md with our team name.
  README.md
Labels: build: 0.0.1 - 05/26/19, pr: process

#46 Added Anthony's picture and Bio to contributors.js
  client/src/components/page/PublicFeed.js
  client/src/reducers/contributors.js
  client/src/statics/images/anthonyPic.jpg
Labels: build: 0.0.1 - 05/26/19, pr: feature

#49 Added StatsPageServlet.java and stats to CustomNavBar.js
  client/src/components/ui/CustomNavBar.js
  client/src/constants/links.js
  server/src/main/java/com/google/codeu/servlets/StatsPageServlet.java
Labels: build: 0.0.2 - 06/02/19, issue: feature
