Repository fluffysheep-codeu/Summer2019-Team30, pull requests merged in 2019-06, with the labels that each got.

#52 Community Page Displays Blank List of Users
  client/src/components/ui/CustomNavBar.js
  client/src/constants/links.js
  client/src/reducers/contributors.js
  server/src/main/java/com/google/codeu/data/Datastore.java
  server/src/main/java/com/google/codeu/servlets/StatsPageServlet.java
  server/src/main/java/com/google/codeu/servlets/UserListServlet.java
Labels: build: 0.0.2 - 06/02/19

#56 Clicking on Stats link prints hello world and opens the Stats page
  client/package-lock.json
  client/src/components/container/Root.js
  client/src/components/page/StatsPage.js
  client/src/constants/links.js
  package-lock.json
  server/src/main/java/com/google/codeu/servlets/StatsPageServlet.java
Labels: build: 0.0.2 - 06/02/19

#57 Stats page now displays the number of messages on the site
  client/src/components/page/StatsPage.js
  server/src/main/java/com/google/codeu/servlets/StatsPageServlet.java
Labels: build: 0.0.2 - 06/02/19, issue: feature

#58 Took the curly braces out of the message string for the stats page
  client/src/components/page/StatsPage.js
Labels: build: 0.0.2 - 06/02/19, pr: process

#59 Creating community page to display every user that has sent a message.
  client/src/components/container/Root.js
  client/src/components/page/CommunityPage.js
  client/src/components/ui/UserItem.js
  client/src/constants/links.js
  server/src/main/java/com/google/codeu/data/Datastore.java
  server/src/main/java/com/google/codeu/servlets/StatsPageServlet.java
  server/src/main/java/com/google/codeu/servlets/UserListServlet.java
Labels: build: 0.0.2 - 06/02/19, pr: feature

#65 Added public feed to show all messages and users pt2
  client/src/components/container/Root.js
  client/src/components/page/PublicFeed.js
  client/src/components/ui/CustomNavBar.js
  client/src/components/ui/Message.js
  client/src/constants/links.js
  server/src/main/java/com/google/codeu/data/Datastore.java
  server/src/main/java/com/google/codeu/servlets/MessageFeedServlet.java
Labels: build: 0.0.2 - 06/02/19, pr: feature

#66 Fixed the old code that was merged
  client/package-lock.json
  server/src/main/java/com/google/codeu/data/Datastore.java
Labels: build: 0.02 - 06/02/19, pr: bug

#68 Display a embedded Google Map on the Home page
  client/package-lock.json
  client/package.json
  client/src/components/page/Home.js
Labels: build: 0.03 - 06/23/19, pr: feature

#69 Added image change command using dangerously..html to display images …
  client/package-lock.json
  client/src/components/page/PublicFeed.js
  client/src/components/ui/Message.js
  server/src/main/java/com/google/codeu/servlets/MessageServlet.java
Labels: build: 0.03 - 06/23/19, pr: feature

#70 Alex maps
  client/package-lock.json
  client/package.json
  client/src/components/markers/MarkersData.js
  client/src/components/page/Home.js
  client/src/components/ui/CustomMap.js
Labels: build: 0.03 - 06/23/19

#74 Added About Me Page
  client/src/components/container/Root.js
  client/src/components/page/UserPage.js
  client/src/constants/links.js
  server/src/main/java/com/google/codeu/data/Datastore.java
  server/src/main/java/com/google/codeu/data/User.java
  server/src/main/java/com/google/codeu/servlets/AboutMeServlet.java
Labels: build: 0.02 - 06/02/19, pr: feature

#76 Fixes failed to execute json on Response on UserPage error
  client/src/components/page/UserPage.js
Labels: build: 0.03 - 06/23/19, pr: bug

#77 Fixed UserItem components need a unique key in Community Page
  client/src/components/page/CommunityPage.js
Labels: build: 0.03 - 06/23/19, pr: bug

#78 Added Home Page UI
  client/src/components/page/Home.js
  client/src/statics/images/background_pasta.jpg
  client/src/statics/images/food_icon.jpg
Labels: build: 0.03 - 06/23/19, pr: feature

#81 Adding Search Bar to Home Page and Nav Bar UI
  client/src/components/page/AboutUs.js
  client/src/components/page/CommunityPage.js
  client/src/components/page/Home.js
  client/src/components/page/PublicFeed.js
  client/src/components/page/StatsPage.js
  client/src/components/page/UserPage.js
  client/src/components/ui/CustomNavBar.js
  client/src/css/index.css
Labels: build: 0.03 - 06/23/19

#82 Added a map and began the making a post section
  client/src/components/page/PublicFeed.js
  client/src/components/ui/CustomMap.js
  server/src/main/java/com/google/codeu/servlets/RestaurantServlet.java
Labels: build: 0.03 - 06/23/19

#83 Fixed a bug from merging
  client/src/components/page/PublicFeed.js
  client/src/components/ui/CustomMap.js
Labels: build: 0.03 - 06/23/19, pr: bug

#91 Storing Users who Sign In and Displaying on Community Page
  client/src/components/page/CommunityPage.js
  client/src/components/page/UserPage.js
  server/src/main/java/com/google/codeu/data/Datastore.java
  server/src/main/java/com/google/codeu/servlets/LoginServlet.java
Labels: build 0.04 - 06/30/19

#75 Added style options for messages and CKEditor Textbox
  client/package-lock.json
  client/package.json
  client/src/components/page/UserPage.js
  client/src/components/ui/Message.js
  server/src/main/java/com/google/codeu/servlets/AboutMeServlet.java
  server/src/main/java/com/google/codeu/servlets/MarkersServlet.java
  server/src/main/java/com/google/codeu/servlets/MessageServlet.java
  server/src/main/java/com/google/codeu/servlets/RestaurantServlet.java
Labels: build: 0.03 - 06/23/19, pr: feature
